### PR TITLE
Merge env config

### PR DESCRIPTION
**Pull request by jaumard**
Part of resolving https://github.com/trailsjs/trails/issues/200

### CODE REVIEW

**Comment by jaumard** [comment]
Trails PR is here : https://github.com/trailsjs/trails/pull/203

**Comment by tjwebb** [comment]
Do the tests in trailsjs/trails#203 cover this?

**Comment by jaumard** [comment]
@tjwebb no as tests only test Trails parts. Tests need to be added here in this PR to tests env config then.

**Comment by jaumard** [comment]
@tjwebb tests is failing because the Trails PR need to be merge and deploy before :) can you do it ? I will update this PR after with new Trails version. Also let me know if tests are enough for you or not.

**Comment by tjwebb** [comment]
@jaumard merged in Trails

**Comment by jaumard** [comment]
@tjwebb don't know why but travisCI didn't publish 1.0.1 on npm :(

**Comment by tjwebb** [comment]
weird, it looks like Travis-CI didn't run at all

**Comment by jaumard** [comment]
@tjwebb yeah see this... All green here :) but Trails tests fails for node 4/5 (problem with fresh project on Hapi/Waterline)

**Comment by jaumard** [comment]
@tjwebb can we merge and deploy this ?

**Comment by jaumard** [comment]
@tjwebb or @konstantinzolotarev can you merge/deploy this ? We need this with @scott-wyatt for settings postgresql as main database and sqlite3 for testing database for circleCI integration :)
Thanks

**Pull request merged**
